[general]
host = "127.0.0.1"
port = 7372

# Use https://scrappey.com/ To manage Anti-Bot Detection during login.
# This will require you enable: `remote_auth_url` under [general] section in your `dragonite_config.toml`.
# Read More: https://github.com/UnownHash/Swirlix-Public?tab=readme-ov-file#requirements
[scrappey]
api_key = ""
# pre_fetch = 20

# [prometheus]
# enabled = true

# [log]
# log_to_file = true
# level = "info"
# max_size = 10
# max_backups = 10
# max_age = 30
# compress = true

# [reminder]
# discord_webhook = ""
# warning = 1000
# critical = 200
